;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Конфигурационный файл плагина Beammeup
; Этот плагин основан на: Плагин Connecticut от MadHunter.
; Debug:                    Уровень отладки, где 0 отключено, 1 — немного, 2 — больше всего.
; TargetSystem:             Целевая система, не может выпрыгнуть отсюда.
; TargetBase:               База для телепортации.
; RestrictedSystem:         Ограниченная система, отсюда невозможно выпрыгнуть.
; DefaultBase:              База, которую можно использовать, если игрок застрял в системе "Beammeup".
[General]
Debug = 2
TargetSystem = Hi03
TargetBase = Hi03_02_base
RestrictedSystem = bw11
DefaultBase = Start01_proxy_base