;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; общие настройки плаща
; DropShieldsCloak: установите для него значение «да», и щит игрока упадет при выполнении /cloak (щиты будут восстанавливаться как обычно)
[General]
DropShieldsCloak=yes
CooldownMsg=yes
PreventFireCloak=no
;CooldownMsgIDS=
DockedErrorIDS=544957
NoCloakDeviceErrorIDS=544956
;CloakPrepareMsgIDS=
;CloakPrepareTimeIDS=
;CooldownTimeRemainingIDS=
;CloakTimeRemainingIDS=

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; настройка устройств маскировки
; Здесь вы должны перечислить все устройства маскировки, которые будут использоваться.
; Формат <cloak item>=<max cloak time>, <cloak "cooldown" time>, <cloak warmup time>
; Если максимальное время маскировки установлено на 0, время бесконечно (обратите внимание, время указано в мс)
[CloakDevices]
cloak_battleship=99999999, 10000, 10000