;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Ограничения на стыковку
; Перечислите названия объектов, которые вы хотите, чтобы игроки имели определенный предмет для стыковки с ним.
; Формат: <Object nickname>=<item nickname>, <необходимое количество элементов, 0 для установленных, отрицательное значение для удаления элемента(ов) из дока>, <сообщение отправлено отклоненному игроку>
[DockRestrictions]
bw06_03=commodity_Key01, 1, Доступ запрещен! Отсутствует лицензия для пропуска