;; M- нумерация амуниции - топ АМУНИЦИИ если сунешь пушку будет кидать две пушки вместо одной
;;; allequip - сколько всего предметов если М12 то всего 13 и так далее ЭТО ОБЯЗАТЕЛЬНОЕ ЧИСЛО
[General]
allequip=1
[CargoName]
M0=