[Settings]
dllname = playercntl.dll
name = Player Control v1.0 by Cannon
shortname = playercntl
maypause = false
mayunload = true

[Restart]
MaxRank = 60
MaxCash = 1000000

[LogItems]
donat_torpedo = donat_torpedo
license_member_ph = license_member_ph

[NewPlayerBanner]
Text = <TRA data="0x40B60002" mask="-1"/><TEXT>Вы можете использовать '/restart parameter' для нового персонажа. Для нового персонажа доступны параметры miner, outcast, corsair, bretonia, gallia, kusari, liberty и rheinland. Введите /helpmenu или /help для получения справки.</TEXT>

[General]
EnableMoveChar = no
EnableRenameMe = yes
EnablePimpShip = yes
EnableRestart = yes
EnableGiveCash = yes
RepDropCost = 350000
StuckMsg = Внимание! Держитесь подальше. Буксировка %player
DiceMsg = %player rolled %number / %max
CoinMsg = %player tossed %result
SmiteMusic = music_victory
DisconnectingPlayersRange = 6800
ReportDisconnectingPlayers = yes
KillDisconnectingPlayers = no
LootDisconnectingPlayers = no
HullDropFactor = 0.0001
CargoDropContainer = big_bomb_1_hit_pts
HullDrop1NickName = commod_big_bomb
HullDrop2NickName = commod_big_bomb
DisconnectMsg = %time: %player пытается задействовать маскировочное устройство
EnableDropRepAndMisc = yes
SpinProtectionMass = 180
SpinProtectionMultiplier = -1.0
EnableEscort = no
EscortedShipMinimumMass = 100000
EscortedShipDamageFactor = 0.0

[Rename]
RenameCost = 10000000
RenameTimeLimit = 86400
MoveCost = 10000000

[GiveCash]
MinTransfer = 100000
MinTime = 172800 ;48 часов
CheatDetection = true ;not use
BlockedSystem = iw09

[RepFixer]
EnableRepFixUpdates = yes
LogRepFixUpdates = no
ItemMustBeMounted = yes

[PurchaseRestrictions]
EnforceIDRestrictions = yes
CheckIDRestrictions = yes

[Message]
CustomHelp = yes
CmdEcho = yes
CmdHide = yes
CmdEchoStyle = 0x00FFFF00
StandardBannerDelay = 1200
SpecialBannerDelay = 3000
DisconnectSwearingInSpaceMsg = %player has been kicked for swearing
DisconnectSwearingInSpaceRange = 5000.0f
SetMsg = yes

[RepFixerItems]
license_chief_jph

[admin_scanner_01]
nf_n_grp = 0.9, 3
py17_n_grp = 0.65, 3

[GoodItemRestrictions]
private_cruiser_torpedo01 = license_py1
vega_l_b = license_member_vega

[ShipItemRestrictions]
eclipse_d = license_py38
V_R = license_py38

[Hooks]
hook = LoadSettings, 3
hook = ClearClientInfo, 3
hook = HkTimerCheckKick, 3
hook = SendDeathMsg, 3
hook = HkIServerImpl::PlayerLaunch, 3
hook = HkIServerImpl::BaseEnter, 3
hook = HkIServerImpl::LocationEnter, 3
hook = HkIServerImpl::DisConnect, 3
hook = HkIServerImpl::CharacterSelect, 3
hook = HkIServerImpl::JumpInComplete, 3
hook = HkIServerImpl::SystemSwitchOutComplete, 3
hook = HkIServerImpl::SPObjCollision, 3
hook = HkIServerImpl::GFGoodBuy, 3
hook = HkIServerImpl::ReqAddItem, 3
hook = HkIServerImpl::ReqChangeCash, 3
hook = HkIServerImpl::ReqSetCash, 3
hook = HkIServerImpl::ReqEquipment, 3
hook = HkIServerImpl::ReqHullStatus, 3
hook = HkIServerImpl::ReqShipArch, 3
hook = HkIServerImpl::TractorObjects, 3
hook = HkIServerImpl::SetTarget, 3
hook = HkIServerImpl::CharacterInfoReq, 3
hook = HkIServerImpl::SubmitChat, 3
hook = HkIServerImpl::GoTradelane, 3
hook = HkIServerImpl::StopTradelane, 3
hook = HkIEngine::Dock_Call, 3
hook = HkCb_AddDmgEntry, 3
hook = HkCb_SendChat, 3
hook = UserCmd_Process, 3
hook = UserCmd_Help, 3
hook = ExecuteCommandString_Callback, 3

;Возможности освещения
[ShipPimper]
cost = 30000000
equip = Blue
equip = DockingLightRed
equip = DockingLightRedSmall
equip = DockingLightpurpleSmall
equip = DockingLightwhiteSmall
equip = DockingLightOrangeSmall
equip = DockingLightGreenSmall
equip = DockingLightBlueSmall
equip = FastLargeBlue
equip = FastLargeRed
equip = FastMediumBlue
equip = FastMediumGreen
equip = FastSmallBlue
equip = FastSmallGreen
equip = FastSmallRed
equip = FastSmallYellow
equip = FastTrackRed
equip = Green
equip = LargeBlue
equip = LargeBlueSource
equip = LargeGreen
equip = LargeOrange
equip = LargeOrangeStrobe
equip = LargeRed
equip = LargeWhite
equip = LargeWhiteSpecial
equip = LargeWhiteStrobe
equip = LargeYellow
equip = LibertyCockpitGlow
equip = LightBlueSpecial
equip = MediumBlue
equip = MediumBlueSource
equip = MediumGreen
equip = MediumOrange
equip = MediumRed
equip = MediumWhite
equip = MediumYellow
equip = MedTrackGreen
equip = Orange
equip = Red
equip = SlowLargeBlue
equip = SlowLargeGreen
equip = SlowLargeRed
equip = SlowLargeWhite
equip = SlowLargeYellow
equip = SlowMediumBlue
equip = SlowMediumGreen
equip = SlowMediumRed
equip = SlowMediumWhite
equip = SlowMediumYellow
equip = SlowSmallBlue
equip = SlowSmallGreen
equip = SlowSmallOrange
equip = SlowSmallPurple
equip = SlowSmallRed
equip = SlowSmallWhite
equip = SlowSmallYellow
equip = SlowXLargeBlue
equip = SlowXLargeGreen
equip = SlowXLargeRed
equip = SmallBlue
equip = SmallGreen
equip = SmallOrange
equip = SmallRed
equip = SmallWhite
equip = SmallYellow
equip = White
equip = WhiteCone
equip = WhiteStationSpecial
equip = Yellow
equip = Purple_average
equip = DockingLightpurpleaverage
equip = MediumRedStrobe
equip = MediumGreenStrobe
equip = MediumYellowStrobe
equip = LargePurpleStrobe
equip = MediumBlueStrobe
equip = SmallWhiteStrobe
equip = LargeGreenSpecial
equip = LargeRedSpecial
equip = LargepurpleSpecial
equip = LargeBlueSpecial
equip = LargeOrangeSpecial
room = ac2a468f_shipdealer
room = b9948088_shipdealer
room = a761ec01_shipdealer
room = a673628d_shipdealer
room = bab91306_shipdealer
room = bdd8e54f_shipdealer
room = a72fbe02_shipdealer
room = 373991f2_shipdealer
room = 72b9b000_shipdealer
room = hi0302_fix_ship

[NoBuy]
Am02_03_Base = commodity_water_of_life

[SystemSensor]
RH06 = lair_power_cell, 4

;Получение местоположения и списка грузов.
;Если это судно имеет нужное оборудование и находится в нужной системе, то разрешите доступ..
;Используйте /net для доступа к сети.
;Hackers=идентификатор оборудования
[SystemSensorRestrictions]
Hackers=DockingLightRed

[Help]
<TRA data="0x00FFFF00" mask="-2"/><TEXT>Список команд:</TEXT>
<TRA data="0x00FFFF00" mask="-2"/><TEXT>Прыжковый двигатель:</TEXT>
<TRA data="0x00FFFF00" mask="-2"/><TEXT>====================</TEXT>
<TRA data="0x00FFFF00" mask="-2"/><TEXT>/sftl</TEXT><TRA data="0x4000FF08" mask="-1"/><TEXT> - прыжок по заданным координатам (пример: /sftl 0 15000 0)</TEXT>

[SwearWords]
Text = fuck
Text = придурок

[GreetingBanner]
Text = <TRA data="0x00FFFF00" mask="-2"/><TEXT>Добро пожаловать на Lizerium сервер!</TEXT>

[StandardBanner]
Text = <TRA data="0xFF920540" mask="-1"/><TEXT>Запрещено атаковать убитого игрока своим убийцей, и наоборот в одной системе в течении 5 минут, исключение - договоренность между игроками.</TEXT>

[StandardBanner]
Text = <TRA data="0x00FFFF09" mask="-1"/><TEXT>Для получения более подробной информации посетите наш сайт: </TEXT><TRA data="0xFFFF0009" mask="-1"/> <TEXT>lizup.ru</TEXT> или группу VK: наш сайт: </TEXT><TRA data="0xFFFF0009" mask="-1"/> <TEXT>vk.com/lizerium_game</TEXT>