;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; general settings
; AntiDockKill:     время защиты от стыковки в мс, начинается, когда игрок полностью отстыковался и может свободно летать.
;                   находясь под защитой Dockkill, игрок не может получить урон от других игроков и сам не может нанести урон другим игрокам.
; AntiF1:           время анти-f1 в мс. Нажатие f1 будет отложZено на это время, если игрок находится в космосе. 
;                   клиент не увидит, что происходит во время задержки. (установите 0, чтобы отключить)
; DisconnectDelay:  аналогично anti-f1, применяется, когда игрок отключается, находясь в космосе. 
;                   корабль игрока останется в космосе в течение этого времени, когда он отключится. 
;                   в течение этого периода он не может повторно подключиться к серверу("ваша учетная запись уже используется" будет отображаться)
; EnableDieMsg: подавить сообщения "Player das died: XXX" и заменить их улучшенными сообщениями о смерти FLHook.
; DisableCharfileEncryption: отключает шифрование charfile (будет сохранено в виде простого ascii-текста). 
;                                       это может привести к проблемам с программами, например, ioncross!
; ChangeCruiseDisruptorBehaviour: установите значение «да», и прерыватели круиза больше не будут влиять на глушение двигателя.
; DisableNPCSpawns: отключает появление всех NPC, пока нагрузка на сервер превышает это значение.
;                   он позволяет вам динамически регулировать количество NPC (установите значение 0, чтобы отключить)
; ReservedSlots: устанавливает количество зарезервированных слотов
; TorpMissileBaseDamageMultiplier: устанавливает множитель урона, когда ракета/торпеда игрока попадает в базу
; MaxGroupSize: изменить максимальный размер группы(default is 8)
[General]
AntiDockKill=25000
AntiF1=60000
DisconnectDelay=0
EnableDieMsg=yes
DisableCharfileEncryption=yes
ChangeCruiseDisruptorBehaviour=no
DisableNPCSpawns=30
ReservedSlots=0
TorpMissileBaseDamageMultiplier=1.0
MaxGroupSize=24

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Настройки плагинов
; LoadAllPlugins: Загружать все плагины при запуске (игнорируя список ниже)
; plugin: Список плагинов, которые должны быть загружены при запуске, если для параметра LoadAllPlugins установлено значение «нет». Одна строка на каждый плагин.

[Plugins]
LoadAllPlugins=yes
;plugin = tempban.dll
;plugin = condata.dll



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Настройки логирования
; Отладка: общее отладочное логирование, создает отладочные файлы с метками времени "flhook_logs/debug/"
; DebugMaxSize: максимальный размер файлов отладочных логов (в МБ)
; LogAdminCommands: логирование всех команд администратора
; LogAdminCommands: логирование всех команд пользователя
; LogConnects: логирование всех подключений
; LogPerformanceTimers: логирование всех таймеров производительности
; TimerThreshold: устанавливает пороговое значение для отправки отчетов по таймерам производительности, время в миллисекундах
[Log]
Debug=yes
DebugMaxSize=100
LogAdminCommands=yes
LogSocketCommands=yes
LogLocalSocketCommands=yes
LogUserCommands=yes
LogConnects=yes
LogPerformanceTimers=yes
TimerThreshold=100


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; kick settings
; AntiBaseIdle: время в секундах, по истечении которого игрок будет выкинут из игры за бездействие на базе/планете, независимо от того, активен он или нет (установите значение 0 для отключения)
; AntiCharMenuIdle: время в секундах, по истечении которого игрок будет выкинут из игры за бездействие в Charmenu (установите значение 0 для отключения)
; PingKick:            максимальный средний пинг в мс, более высокий пинг приводит к кику (установите 0, чтобы отключить)
; PingKickFrame: временной интервал в секундах, за который рассчитывается средний пинг (например, PingKickFrame=30 -> рассчитать
; средний пинг на основе данных пинга за последние 30 секунд)
; FluctKick: максимальное колебание среднего пинга, более высокое колебание приводит к исключению (установите значение 0 для отключения)
; LossKick:            максимальный средний убыток, более высокие потери приводят к удару (set to 0 to disable)
; LossKickFrame:       временной интервал в секундах, в течение которого рассчитывается средний убыток.
; LagKick:             максимальная средняя задержка, более высокая задержка приводит к удару (установите значение 0, чтобы отключить)
; LagDetectionFrame: кадр в обновлениях позиции, в котором вычисляется средняя задержка.
; LagDetectionMinimum: минимальная разница в процентах, после которой обнаруживается задержка; чем выше это значение, тем меньше задержек будет обнаружено.
; KickThreshold:       нагрузка на сервер должна превысить это число, прежде чем игроки будут кикнуты из-за высокой задержки/потери/пинга
[Kick]
AntiBaseIdle=600
AntiCharMenuIdle=600
PingKick=0
PingKickFrame=250
FluctKick=0
LossKick=0
LossKickFrame=250
LagKick=0
LagDetectionFrame=50
LagDetectionMinimum=50
KickThreshold=0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Настройки стиля, эти настройки влияют на внешний вид текстовых сообщений, отправляемых клиенту
; DeathMsgStyle: стиль сообщений о смерти, возникающих в чужих системах, это значение "data" XML-узла TRA
; (пояснение в readme.txt)
; DeathMsgStyleSys: стиль сообщений о смерти, возникающих в системе, в которой в данный момент находится игрок
; DeathMsgTextPlayerKill:
; текст, отображаемый, когда игрок убил другого игрока. %victim будет заменен именем
; жертвы и т. д. Установите значение nothing, чтобы отключить сообщение.

; DeathMsgTextSelfKill:
; текст, отображаемый, когда игрок убил себя
; DeathMsgTextNPC: текст, отображаемый, когда игрок был убит NPC
; DeathMsgTextSuicide:
; текст, отображаемый, когда игрок совершил самоубийство
; DeathMsgTextAdminKill:
; Текст, отображаемый при удалении игрока администратором с помощью команды "kill":
; KickMsg: это XML-строка текста, отображаемого при удалении игрока по определенной причине.

; %reason будет заменено на причину.

; KickMsgPeriod: это период времени в миллисекундах, в течение которого отображается причина, прежде чем игрок будет отключен.
; UserCmdStyle: стиль ответов на команды пользователя.
; AdminCmdStyle: стиль ответов на команды администратора.
[Style]
DeathMsgStyle=0x19198C01
DeathMsgStyleSys=0xFF00FFC3
DeathMsgTextPlayerKill=Игрок уничтожен: %victim убит игроком %killer (%type)
DeathMsgTextSelfKill=Игрок уничтожен: %victim погиб от своего же оружия (%type)
DeathMsgTextNPC=Игрок уничтожен: %victim замочили NPC
DeathMsgTextSuicide=Игрок погиб: %victim покончил жизнь самоубийством
DeathMsgTextAdminKill=Игрок уничтожен: %victim убит машиной смерти
KickMsg=<TRA data="0x0000FF10" mask="-1"/><TEXT>Вы будете кикнуты с сервера по одной из причин. Возможно на компьютере запущен totalcmd, torrent, у вас высокий пинг, либо отсутствует/поврежден файл client.dll, обычно работа антивируса: %reason</TEXT>
KickMsgPeriod=5000
UserCmdStyle=0xFF199B09
UserCmdTypeStyle=0xFFFF0540
UserCmdKeyStyle=0xFFD57E40
UserCmdValueStyle=0x03CF1F00
AdminCmdStyle=0x4000FF08

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Настройки сокета
; Активировано: необходимо установить для включения прослушивания сокета
; Порт: порт, который FLHook должен прослушивать (ASCII)
; WPort: порт, который FLHook должен прослушивать (Unicode), вам также потребуется отправлять команды в формате Unicode
; EPort: порт, который FLHook должен прослушивать (ASCII, зашифрованный), вам также потребуется отправлять команды в зашифрованном виде
; EWPort: порт, который FLHook должен прослушивать (Unicode, зашифрованный), вам также потребуется отправлять команды в зашифрованном виде и в формате Unicode
; Ключ: ключ для шифрования Blowfish
; PassX: пароль
; RightsX: права для этого пароля (см. раздел прав в readme.txt)
; вы можете иметь несколько паролей с различными настройками прав
; они должны быть пронумерованы последовательно с помощью passX/rightX
[Socket]
Activated=yes
Port=1919
WPort=1920
EPort=1921
EWPort=1922
Key=S23333322Key234
Pass0=11111f33sf678f7
Rights0=superadmin
Pass1=455553dfdzwd
Rights1=cash,beam

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Команды пользователя (да = включено)
; SetDieMsg: включить/отключить "/set diemsg"
; SetDieMsgSize: включить/отключить "/set diemsgsize"
; SetChatFont: включить/отключить "/set chatfont"
; Ignore: включить/отключить команды игнорирования
; MaxIgnoreListEntries: максимальное количество записей в списке игнорирования, разрешенное для игрока
; Autobuy: включить/отключить "/autobuy"
; Ping: включить/отключить "/ping" и "/pingtarget"
; Help: включить/отключить "/help"
; DefaultLocalChat: если включено, сообщения, отправляемые в системный чат, принудительно отправляются локально, если это явно не переопределено.
[UserCommands]
SetDieMsg=yes
AudioMsg=yes
ChatTime=yes
SetDieMsgSize=yes
SetChatFont=yes
Ignore=yes
MaxIgnoreListEntries=30
AutoBuy=yes
Ping=yes
Help=yes
DefaultLocalChat=no

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Настройки чата
; SuppressX: текст чата, вводимый игроками, начинающийся с этой строки, будет подавлен, но по-прежнему отображаться в
; в режиме событий. Это упрощает кодирование пользовательской системы внутриигровых диалогов.
[Chat]
;Suppress0=/chat
;Suppress1=/etc

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Настройки nopvp
; SystemX: отключить PvP в этой системе (игроки не могут наносить урон другим игрокам)
[NoPVP]
System2=Start01

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Сообщения о множественных убийствах будут отображаться всякий раз, когда игрок совершает определенное количество убийств подряд
; Активировано: включить/отключить сообщения о множественных убийствах
; Стиль: стиль сообщений о множественных убийствах
; <KillsInARow>=<message>: сообщение будет отображаться в системе и только для игроков, у которых параметр diemsg установлен на
; system/all.
[MultiKillMessages]
Activated=yes
Style=0x00FFFFC3
1=%player первое убийство
2=%player в ярости (2 убийства подряд)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Здесь можно ввести блокировки по IP-адресу/хосту (сообщение будет выведено в flhook_kicks.log при совпадении блокировки)
; BanAccountOnMatch: учетная запись игрока будет заблокирована, если установлено значение «да» и совпадает одна из блокировок ниже (этот параметр должен
; находиться в первой строке [Банны]!)
; просто добавьте блокировки по IP-адресу или имени хоста в этот раздел (без точки с запятой в начале!). Вы можете использовать подстановочные знаки (?,*).
[Bans]
BanAccountOnMatch=No
;13.37.*.*
;*.lamer-isp.net

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; настройки имен
; это используется командой "beam" и позволяет указывать сочетания клавиш.
[Names]
Cambridge = Br03_01_Base 
Mining Glorious = Br05_02_Base 
NanseiComplex = Ku03_04_Base 
